/**
 * Menú Chuzitos Gourmet – Todas nuestras especialidades
 * Fuente: CSV + descripciones proporcionadas
 */

export type MenuItem = {
  title: string;
  description: string;
  price: string;
  category: string;
  img: string;
};

const PLACEHOLDER_IMG = "/assets/images/home-beef/menu/menu-1.jpg";

export const menuItems: MenuItem[] = [
  // PERROS CALIENTES
  {
    title: "Perro Sencillo",
    description: "Pan, salchicha, queso costeño, lechuga, papa ripio, salsa de la casa.",
    price: "9.36",
    category: "PERROS CALIENTES",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_37992/product-media_20251218T201402_7f4ae9ca0446cbc23e71d8d395a98428.jpeg",
  },
  {
    title: "Perro Mexicano",
    description: "Pan, salchicha, queso costeño, lechuga, chimichurri, papa ripio, salsa de la casa.",
    price: "10.40",
    category: "PERROS CALIENTES",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_37993/product-media_20251218T201907_7f4ae9ca0446cbc23e71d8d395a98428__7_.jpeg",
  },
  {
    title: "Perro Hawaiano",
    description: "Pan, salchicha, tocineta, queso costeño, lechuga, piña, papa ripio, salsa de la casa.",
    price: "11.45",
    category: "PERROS CALIENTES",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_37994/product-media_20251218T202134_70aa2a4db7f990373ca9c376323e3dea__8_.jpeg",
  },
  {
    title: "Perro Italiano",
    description: "Pan, salchicha, tocineta, queso costeño, queso mozzarella, lechuga, papa ripio, salsa de la casa.",
    price: "13.55",
    category: "PERROS CALIENTES",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_37995/product-media_20251218T202329_70aa2a4db7f990373ca9c376323e3dea__6_.jpeg",
  },
  {
    title: "Perro Suizo",
    description: "Pan, salchicha suiza, queso costeño, lechuga, papa ripio, salsa de la casa.",
    price: "13.55",
    category: "PERROS CALIENTES",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_37996/product-media_20251218T202423_7f4ae9ca0446cbc23e71d8d395a98428__21_.jpeg",
  },
  {
    title: "Perro Italosuizo",
    description: "Pan, salchicha suiza, tocineta, tomate, queso costeño, queso mozzarella, lechuga, papa ripio, salsa de la casa.",
    price: "15.60",
    category: "PERROS CALIENTES",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_37997/product-media_20251218T202603_7f4ae9ca0446cbc23e71d8d395a98428__26_.jpeg",
  },
  {
    title: "Perro Escocés",
    description: "Pan, salchicha long, maíz, queso costeño, lechuga, papa ripio, pollo desmenuzado, salsa de la casa.",
    price: "13.55",
    category: "PERROS CALIENTES",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_37998/product-media_20251218T202921_7f4ae9ca0446cbc23e71d8d395a98428__15_.jpeg",
  },
  {
    title: "Perro Chuzo de Pollo",
    description: "Pan, salchicha, pechuga, queso costeño, queso mozzarella, lechuga, papa ripio, salsa de la casa.",
    price: "19.09",
    category: "PERROS CALIENTES",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_37999/product-media_20251218T203032_70aa2a4db7f990373ca9c376323e3dea__10_.jpeg",
  },
  {
    title: "Perro Chuzo de Carne",
    description: "Pan, salchicha, lomito, queso costeño, queso mozzarella, lechuga, papa ripio, salsa de la casa.",
    price: "22.00",
    category: "PERROS CALIENTES",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38000/product-media_20251218T203146_70aa2a4db7f990373ca9c376323e3dea__4_.jpeg",
  },
  {
    title: "Perro Chuzo Combinado",
    description: "Pan, salchicha, pechuga, lomito, chorizo, butifarra, queso costeño, queso mozzarella, lechuga, papa ripio, salsa de la casa.",
    price: "23.00",
    category: "PERROS CALIENTES",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Perro%20Chuzo%20Combinado.jpg",
  },
  {
    title: "Perro Ítalo Hawaiano",
    description: "Pan, salchicha long, tocineta, piña, queso costeño, queso mozzarella, lechuga, papa ripio, salsa de la casa.",
    price: "15.60",
    category: "PERROS CALIENTES",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38002/product-media_20251218T203633_7f4ae9ca0446cbc23e71d8d395a98428__16_.jpeg",
  },
  // SÁNDWICH
  {
    title: "Sandwich De Pechuga",
    description: "Todos llevan lechuga, tomate, queso mozzarella y la proteína.",
    price: "18.75",
    category: "SÁNDWICH",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38618/product-media_20251223T191403_sandwin_de_pollo.jpg",
  },
  {
    title: "Sandwich De Lomito",
    description: "Todos llevan lechuga, tomate, queso mozzarella y la proteína.",
    price: "21.84",
    category: "SÁNDWICH",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38619/product-media_20251223T191918_sandwin_de_carne.jpg",
  },
  {
    title: "Sandwich De Pollo Desmenuzado",
    description: "Todos llevan lechuga, tomate, queso mozzarella y la proteína.",
    price: "18.75",
    category: "SÁNDWICH",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38622/product-media_20251223T211122_sandwin_de_pollo_desmenuzado_.jpg",
  },
  {
    title: "Sandwich De Pollo Desmenuzado + Maíz",
    description: "Todos llevan lechuga, tomate, queso mozzarella y la proteína.",
    price: "21.85",
    category: "SÁNDWICH",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38621/product-media_20251223T193015_sandwin_de_pollo_desmenuzado_y_maiz_.jpg",
  },
  {
    title: "Sandwich De Pollo Desmenuzado + Suiza",
    description: "Todos llevan lechuga, tomate, queso mozzarella y la proteína.",
    price: "23.95",
    category: "SÁNDWICH",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38623/product-media_20251223T211157_sandwin_de_pollo_desmenuzado_y_suiza.jpg",
  },
  // SALCHIPAPAS
  {
    title: "Salchipapa Sencilla",
    description: "Papas a la francesa, salchicha, queso costeño, lechuga, papa ripio, salsa de la casa.",
    price: "13.55",
    category: "SALCHIPAPAS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38442/product-media_20251222T133036_7f4ae9ca0446cbc23e71d8d395a98428__1_.jpeg",
  },
  {
    title: "Salchipapa de Pollo",
    description: "Papas a la francesa, salchicha, pollo, queso, lechuga, papa ripio, salsa de la casa.",
    price: "20.79",
    category: "SALCHIPAPAS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38443/product-media_20251222T133114_7f4ae9ca0446cbc23e71d8d395a98428__10_.jpeg",
  },
  {
    title: "Salchipapa Combinana",
    description: "Papas a la francesa, salchicha, pollo, carne, queso, lechuga, papa ripio, salsa de la casa.",
    price: "21.85",
    category: "SALCHIPAPAS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38444/product-media_20251222T133219_7f4ae9ca0446cbc23e71d8d395a98428__6_.jpeg",
  },
  {
    title: "Salchipapa Especial",
    description: "Papas a la francesa, salchicha, carne, chorizo, butifarra, pollo, maíz, queso, lechuga, papa ripio, grille, salsa de la casa.",
    price: "29.00",
    category: "SALCHIPAPAS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38445/product-media_20251222T133303_7f4ae9ca0446cbc23e71d8d395a98428__4_.jpeg",
  },
  {
    title: "Salchipapa Suiza",
    description: "Papas a la francesa, salchicha suiza, queso, lechuga, papa ripio, salsa de la casa.",
    price: "15.05",
    category: "SALCHIPAPAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Salchipapa%20Suiza.jpg",
  },
  {
    title: "Salchipapa Carnes",
    description: "Papas a la francesa, salchicha, carne, queso, lechuga, papa ripio, salsa de la casa.",
    price: "23.00",
    category: "SALCHIPAPAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Salchipapa%20Carnes.jpg",
  },
  // PATACÓN GRATINADO
  {
    title: "Patacon de Pollo",
    description: "Patacón gratinado con pollo.",
    price: "19.79",
    category: "PATACÓN",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38446/product-media_20251222T133348_4218ca1d09174218364162cd0b1a8cc1__1_.jpeg",
  },
  {
    title: "Patacon de Carne y Pollo",
    description: "Patacón gratinado con carne y pollo.",
    price: "19.79",
    category: "PATACÓN",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38447/product-media_20251222T133439_70aa2a4db7f990373ca9c376323e3dea__1_.jpeg",
  },
  {
    title: "Patacon Combinado",
    description: "Patacón gratinado combinado.",
    price: "19.79",
    category: "PATACÓN",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38448/product-media_20251222T133516_70aa2a4db7f990373ca9c376323e3dea.jpeg",
  },
  {
    title: "Patacon de Chorizo",
    description: "Patacón gratinado con chorizo.",
    price: "17.69",
    category: "PATACÓN",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38449/product-media_20251222T133600_7f4ae9ca0446cbc23e71d8d395a98428__13_.jpeg",
  },
  {
    title: "Patacon de Butifarra",
    description: "Patacón gratinado con butifarra.",
    price: "17.69",
    category: "PATACÓN",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38450/product-media_20251222T133635_7f4ae9ca0446cbc23e71d8d395a98428__13_.jpeg",
  },
  {
    title: "Patacón Chori Buti",
    description: "Patacón gratinado con chorizo y butifarra.",
    price: "18.75",
    category: "PATACÓN",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Patac%C3%B3n%20Chori%20Buti.jpg",
  },
  // MAZORCAS
  {
    title: "Mazorca Sencilla",
    description: "Maíz, queso, papa ripio, salsa de la casa.",
    price: "10.40",
    category: "MAZORCAS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38439/product-media_20251222T132658_7f4ae9ca0446cbc23e71d8d395a98428__12_.jpeg",
  },
  {
    title: "Mazorca de Pollo Desmenuzado",
    description: "Maíz, pollo desmenuzado, queso, papa ripio, salsa de la casa.",
    price: "15.60",
    category: "MAZORCAS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38440/product-media_20251222T132749_7f4ae9ca0446cbc23e71d8d395a98428__3_.jpeg",
  },
  {
    title: "Mazorca Suiza",
    description: "Maíz, salchicha suiza, queso, papa ripio, salsa de la casa.",
    price: "15.60",
    category: "MAZORCAS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38441/product-media_20251222T132846_7f4ae9ca0446cbc23e71d8d395a98428__20_.jpeg",
  },
  {
    title: "Mazorca de Carne",
    description: "Maíz, carne, queso, papa ripio, salsa de la casa.",
    price: "22.00",
    category: "MAZORCAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Mazorca%20de%20Carne.jpg",
  },
  // ENTRADAS
  {
    title: "Arepa con Queso y Chimichurri",
    description: "Arepa with cheese and chimichurri.",
    price: "8.35",
    category: "ENTRADAS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38457/product-media_20251222T135626_7f4ae9ca0446cbc23e71d8d395a98428__9_.jpeg",
  },
  {
    title: "Pataconcitos con chicharron",
    description: "Pataconcitos with cheese.",
    price: "0.00",
    category: "ENTRADAS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38458/product-media_20251222T135700_7f4ae9ca0446cbc23e71d8d395a98428__11_.jpeg",
  },
  {
    title: "Picada De Bollo",
    description: "Picada de bollo.",
    price: "7.80",
    category: "ENTRADAS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38459/product-media_20251222T135749_7f4ae9ca0446cbc23e71d8d395a98428__17_.jpeg",
  },
  {
    title: "Pataconcitos con Queso",
    description: "Pataconcitos with cheese.",
    price: "10.39",
    category: "ENTRADAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Pataconcitos%20con%20Queso.jpg",
  },
  {
    title: "Papas a la Francesa Gratinada con Tocineta",
    description: "Papas a la francesa gratinadas con tocineta.",
    price: "11.00",
    category: "ENTRADAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Papas%20a%20la%20Francesa%20Gratinada%20con%20Tocineta.jpg",
  },
  // CHUZO AREPA
  {
    title: "Chuzo Arepa de Pollo",
    description: "Arepa rellena con queso, papa ripio, salsa de la casa y proteína.",
    price: "16.65",
    category: "CHUZO AREPA",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38451/product-media_20251222T135021_7f4ae9ca0446cbc23e71d8d395a98428__5_.jpeg",
  },
  {
    title: "Chuzo Arepa de Carne y Pollo",
    description: "Arepa rellena con queso, papa ripio, salsa de la casa y proteína.",
    price: "17.69",
    category: "CHUZO AREPA",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38452/product-media_20251222T135058_70aa2a4db7f990373ca9c376323e3dea__7_.jpeg",
  },
  {
    title: "Chuzo Arepa Combinada",
    description: "Arepa rellena con queso, papa ripio, salsa de la casa y proteína.",
    price: "17.69",
    category: "CHUZO AREPA",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38453/product-media_20251222T135150_7f4ae9ca0446cbc23e71d8d395a98428__2_.jpeg",
  },
  {
    title: "Chuzo Arepa de Carne",
    description: "Arepa rellena con queso, papa ripio, salsa de la casa y proteína.",
    price: "19.75",
    category: "CHUZO AREPA",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38454/product-media_20251222T135236_7f4ae9ca0446cbc23e71d8d395a98428__22_.jpeg",
  },
  {
    title: "Chuzo Arepa de Chorizo",
    description: "Arepa rellena con queso, papa ripio, salsa de la casa y proteína.",
    price: "15.59",
    category: "CHUZO AREPA",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38455/product-media_20251222T135335_7f4ae9ca0446cbc23e71d8d395a98428__28_.jpeg",
  },
  {
    title: "Chuzo Arepa de Butifarra",
    description: "Arepa rellena con queso, papa ripio, salsa de la casa y proteína.",
    price: "17.69",
    category: "CHUZO AREPA",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38456/product-media_20251222T135442_7f4ae9ca0446cbc23e71d8d395a98428__25_.jpeg",
  },
  {
    title: "Chuzo Arepa Suiza",
    description: "Arepa rellena con queso, papa ripio, salsa de la casa y proteína.",
    price: "15.05",
    category: "CHUZO AREPA",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Chuzo+Arepa+Suiza.jpg",
  },
  {
    title: "Chuzo Arepa Especial",
    description: "Arepa rellena con queso, papa ripio, salsa de la casa y proteína.",
    price: "30.00",
    category: "CHUZO AREPA",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Chuzo%20Arepa%20Especial.jpg",
  },
  // CHUZO DESGRANADO
  {
    title: "Chuzo Desgranado de Pollo",
    description: "Bollo limpio, queso, papa ripio, lechuga, proteína, salsa de la casa.",
    price: "18.75",
    category: "CHUZO DESGRANADO",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38432/product-media_20251222T131605_7f4ae9ca0446cbc23e71d8d395a98428__8_.jpeg",
  },
  {
    title: "Chuzo Desgranado Pollo y Carne",
    description: "Bollo limpio, queso, papa ripio, lechuga, proteína, salsa de la casa.",
    price: "19.75",
    category: "CHUZO DESGRANADO",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38434/product-media_20251222T132045_70aa2a4db7f990373ca9c376323e3dea__5_.jpeg",
  },
  {
    title: "Chuzo Desgranado Combinado",
    description: "Bollo limpio, queso, papa ripio, lechuga, proteína, salsa de la casa.",
    price: "20.79",
    category: "CHUZO DESGRANADO",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38435/product-media_20251222T132144_7f4ae9ca0446cbc23e71d8d395a98428__24_.jpeg",
  },
  {
    title: "Chuzo Desgranado de Carne",
    description: "Bollo limpio, queso, papa ripio, lechuga, proteína, salsa de la casa.",
    price: "20.79",
    category: "CHUZO DESGRANADO",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38433/product-media_20251222T131826_7f4ae9ca0446cbc23e71d8d395a98428__23_.jpeg",
  },
  {
    title: "Chuzo Desgranado de Chorizo",
    description: "Bollo limpio, queso, papa ripio, lechuga, proteína, salsa de la casa.",
    price: "16.65",
    category: "CHUZO DESGRANADO",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38436/product-media_20251222T132312_7f4ae9ca0446cbc23e71d8d395a98428__27_.jpeg",
  },
  {
    title: "Chuzo Desgranado de Butifarra",
    description: "Bollo limpio, queso, papa ripio, lechuga, proteína, salsa de la casa.",
    price: "16.65",
    category: "CHUZO DESGRANADO",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38437/product-media_20251222T132444_7f4ae9ca0446cbc23e71d8d395a98428__19_.jpeg",
  },
  {
    title: "Chuzo Desgranado Especial",
    description: "Bollo limpio, queso, papa ripio, lechuga, proteína, salsa de la casa.",
    price: "30.00",
    category: "CHUZO DESGRANADO",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38438/product-media_20251222T132542_70aa2a4db7f990373ca9c376323e3dea__2_.jpeg",
  },
  {
    title: "Chuzo Desgranado ChoriButi",
    description: "Bollo limpio, queso, papa ripio, lechuga, chorizo y butifarra, salsa de la casa.",
    price: "17.00",
    category: "CHUZO DESGRANADO",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Chuzo+Desgranado+ChoriButi.jpg",
  },
  // ASADOS
  {
    title: "Pechuga a la Brasa",
    description: "Acompañado de papas a la francesa y ensalada.",
    price: "22.89",
    category: "ASADOS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38624/product-media_20251223T211850_asado_de_pollo_.jpg",
  },
  {
    title: "Lomito a la Brasa",
    description: "Acompañado de papas a la francesa y ensalada.",
    price: "29.15",
    category: "ASADOS",
    img: "https://achieveapex-organization-files.s3.us-east-1.amazonaws.com/org_811/products/product_38625/product-media_20251223T211941_asado_de_carne_.jpg",
  },
  // MENÚ INFANTIL
  {
    title: "Salchipapa Jr + Jugo de Cajita",
    description: "Menú infantil con salchipapa y jugo de cajita.",
    price: "10.39",
    category: "MENÚ INFANTIL",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Salchipapa%20Jr%20%2B%20Jugo%20de%20Cajita.jpg",
  },
  {
    title: "Nuggets de Pollo + Jugo de Cajita",
    description: "Menú infantil con nuggets y jugo de cajita.",
    price: "10.39",
    category: "MENÚ INFANTIL",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/menu/Nuggets%20de%20Pollo%20%2B%20Jugo%20de%20Cajita.jpg",
  },
  // BEBIDAS – imágenes Chuzitos S3
  {
    title: "Agua",
    description: "Agua embotellada.",
    price: "2.24",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/agua.png",
  },
  {
    title: "Agua Perrier",
    description: "Agua mineral gasificada Perrier (marca Perrier).",
    price: "3.15",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/perrier.png",
  },
  {
    title: "Coca Cola",
    description: "Refresco Coca Cola.",
    price: "2.24",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/cocacolaregular.png",
  },
  {
    title: "Coca Cola Zero",
    description: "Refresco Coca Cola Zero sin azúcar.",
    price: "2.24",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/cocazero.png",
  },
  {
    title: "Colombiana",
    description: "Refresco Colombiana (Postobón).",
    price: "3.49",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/colombiana.png",
  },
  {
    title: "Diet Coke",
    description: "Refresco Diet Coke.",
    price: "2.24",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/dietcoke.png",
  },
  {
    title: "Frescolita",
    description: "Refresco Frescolita (Coca Cola Company).",
    price: "3.49",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/frescolita.png",
  },
  {
    title: "Sprite",
    description: "Refresco Sprite limón lima.",
    price: "2.15",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/sprite.png",
  },
  {
    title: "Uva",
    description: "Refresco Uva (Postobón).",
    price: "3.15",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/uva.png",
  },
  {
    title: "Jugo de Cajita",
    description: "Jugo de cajita surtido.",
    price: "2.24",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/jugocajita.png",
  },
  {
    title: "Kola Roman",
    description: "Refresco Kola Roman (Postobón).",
    price: "3.36",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/kolaroman.png",
  },
  {
    title: "Malte Polar",
    description: "Malta Polar (Maltín Polar).",
    price: "4.00",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/maltepolar.png",
  },
  {
    title: "Manzana",
    description: "Refresco o jugo sabor manzana.",
    price: "3.36",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/manzana.png",
  },
  {
    title: "Papelón con Limón",
    description: "Limonada venezolana (papelón con limón).",
    price: "5.20",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/papelonconlimon.png",
  },
  {
    title: "Pony Malta",
    description: "Malta Pony Malta (Bavaria).",
    price: "3.36",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/ponymalta.png",
  },
  {
    title: "Quatro",
    description: "Refresco Quatro (Coca Cola).",
    price: "3.36",
    category: "BEBIDAS",
    img: "https://chuzitos.s3.us-west-2.amazonaws.com/bebidas/Bebidas/quatro.png",
  },
];
